# Generated by Django 3.2.25 on 2024-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='f_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование авиакомпании')),
                ('f_from', models.CharField(blank=True, default='', max_length=200, verbose_name='Откуда рейс')),
                ('f_to', models.CharField(blank=True, default='', max_length=200, verbose_name='Куда рейс')),
                ('when_f', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата/время вылета')),
                ('when_t', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата/время прилета')),
                ('seats', models.IntegerField(blank=True, default=0, verbose_name='Количество свободных мест')),
                ('passangers', models.IntegerField(blank=True, default=0, verbose_name='Количество зарег.пассажиров')),
                ('aircraft_type', models.IntegerField(blank=True, default='', max_length=200, verbose_name='Тип ВС')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
    ]
