# Generated by Django 3.2.25 on 2024-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_table',
            name='aircraft_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тип ВС'),
        ),
    ]
