version: '2'

services:

  psql_db:

    build: astra-psql/
    # image: astra_psql

    # ports:
    #   - 5432:5432

    volumes:
      - ./astra-psql/pgdata:/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ticket_to:

    build: astra-py/
    # image: astra_py

    depends_on:
      psql_db:
        condition: service_healthy

    ports:
      - 8000:8000
